[package]
name = "cruddb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.3.1"
tokio = "1.25.0"
mongoose = "0.1.11"
serde = "1.0.152"
bson = "2.5.0"
chrono = "0.4.23"


